[package]
name = "mrml"
version = "0.1.0"
authors = ["Jonian Guveli <jonian@hardpixel.eu>"]
edition = "2018"

[dependencies]
mrml = "1.2.10"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[lib]
name = "mrml"
crate-type = ["cdylib"]
